version: '3'
services:
  database:
    container_name: database
    image: postgis/postgis:13-master
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:9.22
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    networks:
      - directus
      # Only needed if running both openease and CMS locally
      - cms-development-network
    depends_on:
      - cache
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      # Are only set upon initialization
      # Can be changed from the directus admin console
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: '12345678'

      AUTH_PROVIDERS: 'gitlab'

      # Only needed for Single Sign-On (SSO) login
      # Can also be configured for other providers,
      # see: https://docs.directus.io/self-hosted/sso.html
      # AUTH_GITLAB_DRIVER: 'openid'
      # AUTH_GITLAB_ICON: 'gitlab'
      # AUTH_GITLAB_LABEL: 'NeemGit'
      # AUTH_GITLAB_CLIENT_ID: 'TODO'
      # AUTH_GITLAB_CLIENT_SECRET: 'TODO'
      # AUTH_GITLAB_ISSUER_URL: 'https://gitlab.com/.well-known/openid-configuration'
      # AUTH_GITLAB_IDENTIFIER_KEY: 'email'
      # AUTH_GITLAB_ALLOW_PUBLIC_REGISTRATION: 'true'
      # AUTH_GITLAB_DEFAULT_ROLE_ID: 'TODO'

      PUBLIC_URL: 'http://localhost:8055/'

networks:
  directus:
  # Only needed if running both openease and CMS locally
  cms-development-network:
    external: true

volumes:
  uploads:
  db_data:
