version: '3'
services:
  proxy:
    container_name: proxy
    image: linuxserver/swag:2.6.0
    cap_add:
      - NET_ADMIN
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: 'Europe/Berlin'
      URL: '${WEBSITE_URL}'
      VALIDATION: 'http'
      STAGING: '${TEST_DEPLOY}' # set to true in testing/development
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    volumes:
      - proxy_config:/config/nginx/proxy-confs
    networks:
      - directus

  database:
    container_name: database
    image: postgis/postgis:13-master
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: '${POSTGRES_DB_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_DB_PW}'
      POSTGRES_DB: '${POSTGRES_DB_NAME}'

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:9.22
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: '${DIRECTUS_KEY}'
      SECRET: '${DIRECTUS_SECRET}'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: '${POSTGRES_DB_NAME}'
      DB_USER: '${POSTGRES_DB_USER}'
      DB_PASSWORD: '${POSTGRES_DB_PW}'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: '${DIRECTUS_ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${DIRECTUS_ADMIN_PW}'

      AUTH_PROVIDERS: 'gitlab'
      
      AUTH_GITLAB_DRIVER: 'openid'
      AUTH_GITLAB_ICON: 'gitlab'
      AUTH_GITLAB_LABEL: '${GITLAB_INSTANCE_NAME}'
      AUTH_GITLAB_SCOPE: 'openid profile email'
      AUTH_GITLAB_AUTHORIZE_URL: '${GITLAB_INSTANCE_URL}/oauth/authorize'
      AUTH_GITLAB_ACCESS_URL: '${GITLAB_INSTANCE_URL}/oauth/token'
      AUTH_GITLAB_PROFILE_URL: '${GITLAB_INSTANCE_URL}/oauth/userinfo'
      AUTH_GITLAB_CLIENT_ID: '${GITLAB_CLIENT_ID}'
      AUTH_GITLAB_CLIENT_SECRET: '${GITLAB_CLIENT_SECRET}'
      AUTH_GITLAB_ISSUER_URL: '${GITLAB_INSTANCE_URL}/.well-known/openid-configuration'
      AUTH_GITLAB_IDENTIFIER_KEY: 'email'
      AUTH_GITLAB_ALLOW_PUBLIC_REGISTRATION: 'true'
      AUTH_GITLAB_DEFAULT_ROLE_ID: '${GITLAB_DEFAULT_ROLE_ID}'

      PUBLIC_URL: 'https://${WEBSITE_URL}/'

networks:
  directus:

volumes:
  proxy_config:
  uploads:
  db_data:
