name: Shut Down CMS

on: workflow_dispatch

env:
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_HOST: ${{ secrets.SSH_HOST }}

jobs:
  shut-down:
    runs-on: ubuntu-latest
    steps:
      - name: configure ssh
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: | 
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END

      - name: check out repository code
        uses: actions/checkout@v3

      - name: shut-down docker-compose
        run: docker-compose -H "ssh://$SSH_USER@SSH_HOST" down
